/** @type {import('tailwindcss').Config} */
module.exports = {
  // IMPORTANT: Paths to your HTML/JS files so Tailwind knows what to keep
  content: [
    "./src/**/*.html",
    "./src/**/*.js",
    "./src/static/**/*.js"
  ],
  theme: {
    extend: {
      colors: {
        primary: '#3b82f6',
        secondary: '#1e293b',
      }
    },
  },
  plugins: [
    // This plugin styles the HTML generated by marked.js automatically
    require('@tailwindcss/typography'),
  ],
}
